### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by EarthMass** [liubobo/automation#4]
操作“运行 Shell 脚本”遇到了错误：“Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named automation”

**Comment by liubobo** [comment]
没有执行脚本安装

**Comment by liubobo** [comment]
详见说明

**Comment by liubobo** [comment]
> 操作“运行 Shell 脚本”遇到了错误：“Traceback (most recent call last):
> File "", line 1, in 
> ImportError: No module named automation”

不好意思，Mac新系统的python执行路径变了，用下面的脚本执行
cd automation/project && sudo /usr/bin/python setup.py develop&&sudo python setup.py develop
